[project]
name = "tk-base-utils"
version = "0.3.7"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.11.7",
]

# 关键在这里：指定 package-data
[tool.setuptools.package-data]
"example" = ["*.example"]
